# Generated by Django 4.1.5 on 2023-01-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Patient', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='dischargetime_patien',
            new_name='dischargetime_patient',
        ),
    ]
